---
  swagger: "2.0"
  info: 
    version: "1.0.0"
    title: "LogReaderApp"
    description: "Describes LogReader endopoints"
  host: "logreader.io"
  basePath: "/"
  schemes: 
    - "http"
  consumes: 
    - "application/json"
  produces: 
    - "application/json"
  paths: 
    /log: 
      get: 
        description: "Returns all log entries from the system"
        produces: 
          - "application/json"
        responses: 
          "200":
            description: "A list of log entries"
            schema: 
              type: "array"
              items: 
                $ref: "#/definitions/LogEntry"
  definitions: 
    LogEntry: 
      type: "object"
      properties: 
        ip: 
          type: "string"
        date:
          type: "string"
        request:
          type: "string"
        response: 
          type: "integer"
          format: "int32"
        userAgent: 
          type: "string"
